vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("n", "L", "<cmd>bnext<cr>")
vim.keymap.set("n", "H", "<cmd>bprev<cr>")
vim.keymap.set("n", "<C-left>", "<cmd>vertical resize -2<cr>")
vim.keymap.set("n", "<C-right>", "<cmd>vertical resize +2<cr>")
vim.keymap.set("n", "sv", "<cmd>vsplit<cr>")
vim.keymap.set("n", "sh", "<cmd>split<cr>")
vim.keymap.set("n", "q", "<cmd>close<cr>")
vim.keymap.set("n", "bd", "<cmd>bd<cr>")
vim.keymap.set("n", "<leader>fm", require("conform").format)
vim.keymap.set("n", "f", require("flash").jump)
vim.keymap.set("v", "f", require("flash").jump)
vim.keymap.set("n", "cr", "<cmd>Lspsaga rename<cr>")
vim.keymap.set("n", "K", "<cmd>Lspsaga hover_doc<cr>")
vim.keymap.set("n", "gI", "<cmd>Lspsaga finder imp<cr>")
vim.keymap.set("n", "gD", "<cmd>Lspsaga peek_definition<cr>")
vim.keymap.set("n", "gT", "<cmd>Lspsaga peek_type_definition<cr>")
vim.keymap.set("n", "]d", "<cmd>Lspsaga diagnostic_jump_next<cr>")
vim.keymap.set("n", "[d", "<cmd>Lspsaga diagnostic_jump_prev<cr>")
vim.keymap.set("n", "gr", "<cmd>Lspsaga finder ref<cr>")
vim.keymap.set("n", "<leader>o", "<cmd>Lspsaga outline<cr>")
vim.keymap.set("n", "<leader>ca", "<cmd>Lspsaga code_action<cr>")
vim.keymap.set("t", "<ESC>", "<C-\\><C-n>")
vim.keymap.set("n", "<leader>t", "<cmd>terminal<cr>")
vim.keymap.set("n", "<C-t>", "<cmd>ToggleTerm<cr>")
vim.keymap.set("t", "<C-t>", "<cmd>ToggleTerm<cr>")
vim.keymap.set("n", "<C-/>", "<cmd>ToggleTerm direction=float<cr>")
vim.keymap.set("t", "<C-/>", "<cmd>ToggleTerm direction=float<cr>")
vim.keymap.set("t", "<A-h>", "<C-\\><C-N><C-w>h")
vim.keymap.set("t", "<A-j>", "<C-\\><C-N><C-w>j")
vim.keymap.set("t", "<A-k>", "<C-\\><C-N><C-w>k")
vim.keymap.set("t", "<A-l>", "<C-\\><C-N><C-w>l")
vim.keymap.set("i", "<A-h>", "<C-\\><C-N><C-w>h")
vim.keymap.set("i", "<A-j>", "<C-\\><C-N><C-w>j")
vim.keymap.set("i", "<A-k>", "<C-\\><C-N><C-w>k")
vim.keymap.set("i", "<A-l>", "<C-\\><C-N><C-w>l")
vim.keymap.set("n", "<A-h>", "<C-w>h")
vim.keymap.set("n", "<A-j>", "<C-w>j")
vim.keymap.set("n", "<A-k>", "<C-w>k")
vim.keymap.set("n", "<A-l>", "<C-w>l")
vim.keymap.set("n", "<leader>ff", "<cmd>Pick files<cr>")
vim.keymap.set("n", "<leader>fb", "<cmd>Pick buffers<cr>")
vim.keymap.set("n", "<leader>fh", "<cmd>Pick help<cr>")
vim.keymap.set("n", "<leader>fg", "<cmd>Pick grep_live<cr>")
vim.keymap.set("n", "<leader>fd", "<cmd>Pick diagnostic<cr>")
vim.keymap.set("n", "<leader>fe", function()
	require("mini.files").open()
end)
vim.keymap.set("n", "<leader>fr", function()
	require("mini.files").reset()
end)
