local opts = vim.o
opts.number = true
opts.relativenumber = true
opts.signcolumn = "yes"
opts.ignorecase = true
opts.smartcase = true
opts.tabstop = 4
opts.shiftwidth = 4
opts.softtabstop = 4
opts.expandtab = true
opts.smarttab = true
opts.cursorline = true
opts.ruler = true
opts.timeoutlen = 300
opts.clipboard="unnamedplus"
